if (typeof FSWebChatIn === 'undefined') {
    FSWebChatIn = {};
}

FSWebChatIn.lang = {};

FSWebChatIn.lang.en = {
    definition: 'English',
    main: {
        in_conv: '&nbsp;- In Conversation',
        connect_serv: '&nbsp;- trying connect to server',
        submit_message: 'Fill in the fields to start chatting!',
        name: 'Name',
        email: 'Email',
        message: 'Message',
        start_dialog: 'Start Dialog',
        send_file: 'Send File',
        rate_chat: 'Rate Chat',
        notification_sound: 'Notification Sound',
        send_chat_email: 'Send Chat by Email',
        private_mode: 'Private Mode (dont save user data)',
        end_chat: 'End Chat',
        rating_box: 'Tell us how good we are!',
        send_rating: 'Send Rating',
        cancel_rating: 'Cancel',
        dialog_end: 'Conversation ended successfully!',
        resume_dialog: 'Resume',
        close_dialog: 'Close',
        loading_info: 'Loading previous interactions...',
        expire_alert_1: 'Client inactivity alert!',
        expire_alert_2: 'Its going to close in ',
        expire_alert_3: ' seconds!',
        resume_expire: 'Resume',
        close_expire: 'Close',
        expire_autoclose: 'This dialog was automatically closed due to client inactivity!',
        expire_autoclose_ok: 'OK',
        offline_message: 'Submit a message and an operator will reply by email whenever possible!',
        submit_offline_message: 'Submit Message',
        write_message: 'write message (500 characters max)',
        write_comment: 'write comment',
        ticket_title_error: 'Error',
        ticket_msg_error: 'An error occurred while creating ticket.',
        ticket_title_success: 'Success ',
        ticket_msg_success: 'Ticket successfully created. Ticked ID: ',
        file_upload_error_size: 'File size exceeds maximum allowed.',
        file_upload_error_ext: 'File extension not allowed.',
        active_lang: 'Language',
        chat_id: 'Chat ID',
        change_name: 'Change Name',
        options: 'Options',
        change_name_box: 'Insert new name.',
        current_name: 'Current Name',
        new_name: 'New Name',
        change_name_ok: 'Change',
        change_name_cancel: 'Cancel',
        status_offline_title: 'Error',
        status_offline_msg: 'Webchat is out of schedule.'
    },
    ractive: {
        joined: 'joined',
        left: 'left',
        processing: 'Processing...',
        sending: 'Sending...',
        rating: '[RATING]',
        comment: '[COMMENT]',
        rate_chat: 'Please, rate this chat.',
        rate_chat_btn: 'Rate Chat',
        file_upload_client_ok: 'File Uploaded!',
        file_upload_agent_ok: 'File Ready! Click to Download.',
        file_upload_fail: 'File Transfer Failed!',
        file_upload_client_loading: 'Uploading File...',
        file_upload_agent_loading: 'Agent is Sending a File...',
        facebook_attach: 'New Facebook Attachment(s)',
        facebook_attach_type: 'Attachment Type',
        facebook_attach_transfer: 'Open / Transfer'
    },
    system: {
        mail_send_ok: 'Email successfully sent!',
        mail_send_error: 'An error occurred sending email.'
    }
};

FSWebChatIn.lang.pt = {
    definition: 'Português',
    main: {
        in_conv: '&nbsp;- Em Conversação',
        connect_serv: '&nbsp;- a reestabelecer a ligação',
        submit_message: 'Preencha o formulário para iniciar!',
        name: 'Nome',
        email: 'Email',
        message: 'Mensagem',
        start_dialog: 'Iniciar Conversação',
        send_file: 'Enviar Ficheiro',
        rate_chat: 'Avaliar Chat',
        notification_sound: 'Som de Notificação',
        send_chat_email: 'Enviar Conversação por Email',
        private_mode: 'Modo Privado (não guardar dados de utilizador)',
        end_chat: 'Terminar Conversação',
        rating_box: 'Diga-nos o quão bom somos!',
        send_rating: 'Enviar',
        cancel_rating: 'Cancelar',
        dialog_end: 'A conversação foi terminada!',
        resume_dialog: 'Retomar',
        close_dialog: 'Fechar',
        loading_info: 'A carregar conversação...',
        expire_alert_1: 'Alerta de inatividade do utilizador!',
        expire_alert_2: 'A conversação vai terminar em ',
        expire_alert_3: ' segundos!',
        resume_expire: 'Retomar',
        close_expire: 'Fechar',
        expire_autoclose: 'Esta conversação foi automaticamente terminada devido à inatividade do utilizador!',
        expire_autoclose_ok: 'OK',
        offline_message: 'Escreva uma mensagem e um operador irá entrar em contato por email assim que possível!',
        submit_offline_message: 'Enviar Mensagem',
        write_message: 'escreva a mensagem (máx. 500 caracteres)',
        write_comment: 'escreva um comentário',
        ticket_title_error: 'Erro',
        ticket_msg_error: 'Ocorreu um erro ao criar o ticket.',
        ticket_title_success: 'Sucesso ',
        ticket_msg_success: 'Ticket criado com sucesso. Ticked ID: ',
        file_upload_error_size: 'O tamanho do ficheiro excede o limite autorizado.',
        file_upload_error_ext: 'A extensão do ficheiro não é permitida.',
        active_lang: 'Idioma',
        chat_id: 'ID do Chat',
        change_name: 'Alterar Nome',
        options: 'Opções',
        change_name_box: 'Insira o novo nome.',
        current_name: 'Nome Atual',
        new_name: 'Novo Nome',
        change_name_ok: 'Alterar',
        change_name_cancel: 'Cancelar',
        status_offline_title: 'Erro',
        status_offline_msg: 'O webchat encontra-se fora de horário.'
    },
    ractive: {
        joined: 'entrou',
        left: 'saiu',
        processing: 'A processar...',
        sending: 'A enviar...',
        rating: '[AVALIAÇÃO]',
        comment: '[COMENTÁRIO]',
        rate_chat: 'Por favor, avalie este chat.',
        rate_chat_btn: 'Avaliar Chat',
        file_upload_client_ok: 'O ficheiro foi enviado!',
        file_upload_agent_ok: 'O ficheiro está pronto! Clique para transferir.',
        file_upload_fail: 'A transferência falhou!',
        file_upload_client_loading: 'A enviar ficheiro...',
        file_upload_agent_loading: 'O operador está a enviar um ficheiro...',
        facebook_attach: 'Novo(s) Anexo(s) via Facebook',
        facebook_attach_type: 'Tipo de Anexo',
        facebook_attach_transfer: 'Ver / Transferir'
    },
    system: {
        mail_send_ok: 'Email enviado com sucesso!',
        mail_send_error: 'Ocorreu um erro ao enviar o email.'
    }
};

FSWebChatIn.lang.es = {
    definition: 'Español',
    main: {
        in_conv: '&nbsp;- En Conversación',
        connect_serv: '&nbsp;- intentando conectarse al servidor',
        submit_message: 'Escriba un mensaje para empezar!',
        name: 'Nombre',
        email: 'Correo electrónico',
        message: 'Mensaje',
        start_dialog: 'Iniciar una Conversación',
        send_file: 'Enviar Archivo',
        rate_chat: 'Calificar Chat',
        notification_sound: 'Sonido de Notificación',
        send_chat_email: 'Enviar mensaje por correo electrónico',
        private_mode: 'Modo privado (no guardar datos de usuario)',
        end_chat: 'Chat Finalizado',
        rating_box: '¡Cuéntanos lo buenos que somos!',
        send_rating: 'Enviar Calificación',
        cancel_rating: 'Cancelar',
        dialog_end: '¡La conversación terminó con éxito!',
        resume_dialog: 'Continuar',
        close_dialog: 'Cerrar',
        loading_info: 'Cargando las interacciones anteriores...',
        expire_alert_1: '¡Alerta de inactividad del cliente!',
        expire_alert_2: '¡Se va a cerrar en ',
        expire_alert_3: ' segundos!',
        resume_expire: 'Continuar',
        close_expire: 'Cerrar',
        expire_autoclose: 'Este diálogo se cerró automáticamente debido a la inactividad del cliente.',
        expire_autoclose_ok: 'OK',
        offline_message: '¡Envíe un mensaje y un operador contestará por correo electrónico siempre que sea posible!',
        submit_offline_message: 'Enviar Mensaje',
        write_message: 'escribir mensaje (máximo 500 caracteres)',
        write_comment: 'escribe un comentario',
        ticket_title_error: 'Error',
        ticket_msg_error: 'Se ha producido un error al crear el ticket.',
        ticket_title_success: 'Éxito ',
        ticket_msg_success: 'Ticket creado correctamente. Ticked ID: ',
        file_upload_error_size: 'El tamaño del archivo supera el máximo permitido.',
        file_upload_error_ext: 'No se permite la extensión de archivo.',
        active_lang: 'Idioma',
        chat_id: 'Chat ID',
        change_name: 'Cambiar Nombre',
        options: 'Opciones',
        change_name_box: 'Insertar nuevo nombre.',
        current_name: 'Nombre Actual',
        new_name: 'Nuevo Nombre',
        change_name_ok: 'Cambio',
        change_name_cancel: 'Cancelar',
        status_offline_title: 'Error',
        status_offline_msg: 'Webchat está fuera de horario.'
    },
    ractive: {
        joined: 'unido',
        left: 'salido',
        processing: 'Tratamiento...',
        sending: 'Enviando...',
        rating: '[RATING]',
        comment: '[COMMENT]',
        rate_chat: 'Por favor, califique este chat.',
        rate_chat_btn: 'Calificar Chat',
        file_upload_client_ok: 'Archivo Subido!',
        file_upload_agent_ok: 'Archivo Listo! Haga clic para descargar.',
        file_upload_fail: '¡Error en la transferencia de archivos!',
        file_upload_client_loading: 'Subiendo Archivo...',
        file_upload_agent_loading: 'El agente está enviando un archivo...'
    },
    system: {
        mail_send_ok: 'Correo electrónico enviado correctamente.',
        mail_send_error: 'Se ha producido un error al enviar un correo electrónico.'
    }
};

FSWebChatIn.lang.fr = {
    definition: 'Français',
    main: {
        in_conv:"&nbsp;- En conversation",
        connect_serv:"&nbsp;- L'établissement à nouveau la connexion",
        submit_message:"Remplissez le formulaire pour commencer!",
        name:"Nom",
        email:"Email",
        message:"message",
        start_dialog:"Commencer la conversation",
        send_file:"Envoyer le fichier",
        rate_chat:"Évaluer la session de chat",
        notification_sound:"Son de notification",
        send_chat_email:"Envoyer la conversation par e-mail",
        private_mode:"Mode privé (ne pas enregistrer les données utilisateur)",
        end_chat:"Mettre fin à la conversation",
        rating_box:"Dites-nous comment nous sommes bons!",
        send_rating:"Envoyer",
        cancel_rating:"Annuler",
        dialog_end:"La conversation est terminée!",
        resume_dialog:"Reprendre",
        close_dialog:"Fermer",
        loading_info:"Chargement de la conversation …",
        expire_alert_1:"Alerte d'inactivité de l'utilisateur!",
        expire_alert_2:"La conversation se terminera par",
        expire_alert_3:"secondes!",
        resume_expire:"Reprendre",
        close_expire:"Fermer",
        expire_autoclose:"Cette conversation a été automatiquement terminée en raison de l'inactivité de l'utilisateur!",
        expire_autoclose_ok:"OK",
        offline_message:"Écrivez un message et l'opérateur vous contactera par courrier électronique dès que possible!",
        submit_offline_message:"Envoyer un message",
        write_message:"écrire le message (max 500 caractères)",
        write_comment:"écrire un commentaire",
        ticket_title_error:"Erreur",
        ticket_msg_error:"Une erreur s'est produite lors de la création de votre ticket.",
        ticket_title_success:"succès",
        ticket_msg_success:"Ticket créé avec succès. ID Ticked:",
        file_upload_error_size:"La taille du fichier dépasse la limite autorisée.",
        file_upload_error_ext:"L'extension de fichier n'est pas autorisée.",
        active_lang:"Langue",
        chat_id:"ID de session de chat",
        change_name:"Changer le nom",
        options:"Options",
        change_name_box:"Entrez le nouveau nom.",
        current_name:"Nom actuel",
        new_name:"Nouveau nom",
        change_name_ok:"Modifier",
        change_name_cancel:"Annuler",
        status_offline_title:"Erreur",
        status_offline_msg:"Le webchat est en dehors des heures d'ouverture"
    },
    ractive: {
        joined:"Rejoint",
        left:"A quitté",
        processing:"en traitement",
        sending:"Envoi en cours …",
        rating:"[Évaluation]",
        comment:"[COMMENTAIRE]",
        rate_chat:"S'il vous plaît noter cette session de chat.",
        rate_chat_btn:"Évaluer session de conversation",
        file_upload_client_ok:"Le fichier a été envoyé!",
        file_upload_agent_ok:"Le fichier est prêt! Cliquez pour télécharger.",
        file_upload_fail:"Le téléchargement a échoué!",
        file_upload_client_loading:"Envoi de fichier …",
        file_upload_agent_loading:"L'opérateur est l'envoi un fichier …",
        facebook_attach:"Nouvelle (s) jointe (s) via Facebook",
        facebook_attach_type:"Type de fichier attaché",
        facebook_attach_transfer:"Voir / Télécharger"
    },
    system: {
        mail_send_ok:"Email envoyé avec succès!",
        mail_send_error:"Une erreur s'est produite lors de l'envoi du courrier électronique."
    }
};

FSWebChatIn.lang.de = {
    definition: 'Deutsch',
    main: {
        in_conv:"&nbsp;- Im gespräch",
        connect_serv:"&nbsp;- Festlegung verbindung wieder",
        submit_message:"Füllen Sie das Formular aus, um zu beginnen!",
        name:"Name",
        email:"Email",
        message:"Nachricht",
        start_dialog:"Starten Sie die Unterhaltung",
        send_file:"Datei senden",
        rate_chat:"Bewerten Sie die Chat-Sitzung",
        notification_sound:"Benachrichtigungssound",
        send_chat_email:"Senden Sie eine Konversation per E-Mail",
        private_mode:"Private-Modus (nicht speichern Benutzerdaten)",
        end_chat:"Beende die Konversation",
        rating_box:"Sagen Sie uns, wie gut wir sind!",
        send_rating:"Senden",
        cancel_rating:"stornieren",
        dialog_end:"Das Gespräch ist vorbei!",
        resume_dialog:"Fortsetzen",
        close_dialog:"Schließen",
        loading_info:"Konversation wird geladen …",
        expire_alert_1:"Benutzer-Inaktivitätsalarm!",
        expire_alert_2:"Die Konversation wird enden",
        expire_alert_3:"Sekunden!",
        resume_expire:"Fortsetzen",
        close_expire:"Schließen",
        expire_autoclose:"Diese Konversation wurde aufgrund von Inaktivität des Benutzers automatisch beendet!",
        expire_autoclose_ok:"OK",
        offline_message:"Schreiben Sie eine Nachricht und der Betreiber wird Sie so bald wie möglich per E-Mail kontaktieren!",
        submit_offline_message:"Nachricht senden",
        write_message:"schreibe die Nachricht (max. 500 Zeichen)",
        write_comment:"Schreibe einen Kommentar",
        ticket_title_error:"Fehler",
        ticket_msg_error:"Beim Erstellen Ihres Tickets ist ein Fehler aufgetreten.",
        ticket_title_success:"Erfolg",
        ticket_msg_success:"Ticket erfolgreich erstellt Ticked ID:",
        file_upload_error_size:"Die Dateigröße überschreitet das zulässige Limit.",
        file_upload_error_ext:"Die Dateierweiterung ist nicht erlaubt.",
        active_lang:"Sprache",
        chat_id:"Chat-Sitzungs-ID",
        change_name:"Änderung Name",
        options:"Optionen",
        change_name_box:"Geben Sie den neuen Namen ein.",
        current_name:"Aktueller Name",
        new_name:"Neuer Name",
        change_name_ok:"Veränderung",
        change_name_cancel:"stornieren",
        status_offline_title:"Fehler",
        status_offline_msg:"Der Webchat ist außerhalb von Öffnungszeiten"
    },
    ractive: {
        joined:"Beigetreten",
        left:"Hat verlassen",
        processing:"in der Verarbeitung",
        sending:"Senden läuft …",
        rating:"[Bewertung]",
        comment:"[Kommentar]",
        rate_chat:"Bitte bewerte diese Chat-Sitzung.",
        rate_chat_btn:"Bewerten Sie Chat-Sitzung",
        file_upload_client_ok:"Die Datei wurde hochgeladen!",
        file_upload_agent_ok:"Die Datei ist fertig! Klicken Sie zum Download bereit.",
        file_upload_fail:"Download fehlgeschlagen!",
        file_upload_client_loading:"Datei wird hochgeladen…",
        file_upload_agent_loading:"Der Betreiber ist das Senden einer Datei …",
        facebook_attach:"Neue Anlage (n) über Facebook",
        facebook_attach_type:"Angehängter Dateityp",
        facebook_attach_transfer:"Ansicht / Transfer"
    },
    system: {
        mail_send_ok:"E-Mail erfolgreich gesendet!",
        mail_send_error:"Beim Senden der E-Mail ist ein Fehler aufgetreten."
    }
};